from talon.voice import Word, Context, Key, Rep, RepPhrase, Str, press
from talon import app, ctrl, clip, ui
import string

from user.utility import (
    parse_word,
    parse_words,
    rot13,
    sentence_text,
    surround,
    text,
    word,
    vocab,
)


def copy_bundle(m):
    bundle = ui.active_app().bundle
    clip.set(bundle)
    app.notify('Copied app bundle', body='{}'.format(bundle))

ctx = Context("input")
ctx.vocab = vocab
ctx.keymap(
    {
        "say <dgndictation> [over]": text,
        "sentence <dgndictation> [over]": sentence_text,
        "comma <dgndictation> [over]": [", ", text],
        "period <dgndictation> [over]": [". ", sentence_text],
        "more <dgndictation> [over]": [" ", text],
        "word <dgnwords>": word,
        "slap": [Key("cmd-right enter")],
        "question [mark]": "?",
        "tilde": "~",
        "(bang | exclamation point)": "!",
        "dollar [sign]": "$",
        "downscore": "_",
        "colon": ":",
        "(paren | left paren)": "(",
        "(rparen | are paren | right paren)": ")",
        "(brace | left brace)": "{",
        "(rbrace | are brace | right brace)": "}",
        "(angle | left angle | less than)": "<",
        "(rangle | are angle | right angle | greater than)": ">",
        "(star | asterisk)": "*",
        "(pound | hash [sign] | octo | thorpe | number sign)": "#",
        "percent [sign]": "%",
        "caret": "^",
        "at sign": "@",
        "(and sign | ampersand | amper)": "&",
        "pipe": "|",
        "(dubquote | double quote)": '"',
        "triple quote": "'''",
        "swipe": ", ",
        "(space | skoosh)": " ",
        # "(dot dot | dotdot)": "..",
        # "cd": "cd ",
        # "cd talon home": "cd {}".format(TALON_HOME),
        # "cd talon user": "cd {}".format(TALON_USER),
        # "cd talon plugins": "cd {}".format(TALON_PLUGINS),
        # "run make (durr | dear)": "mkdir ",
        # "run git": "git ",
        # "run git clone": "git clone ",
        # "run git diff": "git diff ",
        # "run git commit": "git commit ",
        # "run git push": "git push ",
        # "run git pull": "git pull ",
        # "run git status": "git status ",
        # "run git add": "git add ",
        # "run (them | vim)": "vim ",
        # "run ellis": "ls\n",
        # "dot pie": ".py",
        # "run make": "make\n",
        # "run jobs": "jobs\n",
        # "const": "const ",
        # "static": "static ",
        "(args | arguments)": ["()", Key("left")],
        "index": ["[]", Key("left")],
        "block": [" {}", Key("left enter enter up")],
        "empty array": "[]",
        "(empty dict | empty dictionary)": "{}",
        "plus": "+",
        "arrow": "->",
        "call": "()",
        "indirect": "&",
        "dereference": "*",
        "(op equals | assign)": " = ",
        "set to": " := ",
        "op (minus | subtract)": " - ",
        "op (plus | add)": " + ",
        "op (times | multiply)": " * ",
        "op divide": " / ",
        "op mod": " % ",
        "[op] (minus | subtract) equals": " -= ",
        "[op] (plus | add) equals": " += ",
        "[op] (times | multiply) equals": " *= ",
        "[op] divide equals": " /= ",
        "[op] mod equals": " %= ",
        "(op | is) greater [than]": " > ",
        "(op | is) less [than]": " < ",
        "(op | is) equal": " == ",
        "(op | is) not equal": " != ",
        "(op | is) greater [than] or equal": " >= ",
        "(op | is) less [than] or equal": " <= ",
        "(op (power | exponent) | to the power [of])": " ** ",
        "op and": " && ",
        "op or": " || ",
        "[op] (logical | bitwise) and": " & ",
        "[op] (logical | bitwise) or": " | ",
        "(op | logical | bitwise) (ex | exclusive) or": " ^ ",
        "[(op | logical | bitwise)] (left shift | shift left)": " << ",
        "[(op | logical | bitwise)] (right shift | shift right)": " >> ",
        "(op | logical | bitwise) and equals": " &= ",
        "(op | logical | bitwise) or equals": " |= ",
        "(op | logical | bitwise) (ex | exclusive) or equals": " ^= ",
        "[(op | logical | bitwise)] (left shift | shift left) equals": " <<= ",
        "[(op | logical | bitwise)] (right shift | shift right) equals": " >>= ",
        "new window": Key("cmd-n"),
        "next window": Key("cmd-`"),
        "(last | previous) window": Key("cmd-shift-`"),
        "(next app | swick)": Key("cmd-tab"),
        "(last | previous) app": Key("cmd-shift-tab"),
        "next tab": Key("ctrl-tab"),
        "new tab": Key("cmd-t"),
        "(dizzle | undo)": Key("cmd-z"),
        "last tab": Key("ctrl-shift-tab"),
        "next space": Key("cmd-alt-ctrl-right"),
        "(last | previous) space": Key("cmd-alt-ctrl-left"),
        'copy active bundle': copy_bundle,
    }
)
